service: my-simple-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  environment:
    TRANSMITTER_KEY_ID: ${env:SEED_PHRASE, self:custom.envs.TRANSMITTER_KEY_ID, ''}
    SEED_PHRASE: ${env:SEED_PHRASE, self:custom.envs.SEED_PHRASE, ''}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "kms:Sign"
            - "kms:GetPublicKey"
          Resource: "*"
package:
  individually: true

functions:
  sign:
    handler: src/handler.sign
    events:
      - httpApi:
          path: /sign
          method: POST
  data:
    handler: src/handler.sendData
    events:
      - httpApi:
          path: /data
          method: GET

plugins:
  - serverless-esbuild

custom:
  envs: ${ssm:/aws/reference/secretsmanager/backend/prod}
  esbuild:
    bundle: true
    minify: false
    nativeZip: true
    packager: yarn
    treeShaking: true
    concurrency: 1
    external:
      - pg
