service: my-simple-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    nativeZip: true
    packager: yarn
    treeShaking: true
    concurrency: 1
    external:
      - pg